import { pgTable, uuid, varchar, boolean, integer, timestamp, index, real } from 'drizzle-orm/pg-core';

export const offers = pgTable('offers', {
  id:             uuid('id').primaryKey().defaultRandom(),
  title:          varchar('title',          { length: 255 }).notNull(),
  subtitle:       varchar('subtitle',       { length: 255 }).notNull().default(''),
  description:    varchar('description',    { length: 500 }),
  tag:            varchar('tag',            { length: 64  }).notNull().default('LIMITED OFFER'),
  discountText:   varchar('discount_text',  { length: 64  }).notNull().default(''),
  bgColor:        varchar('bg_color',       { length: 16  }).notNull().default('#5B3EF5'),
  imageUrl:       varchar('image_url',      { length: 1000 }),
  altText:        varchar('alt_text',       { length: 255 }),
  ctaText:        varchar('cta_text',       { length: 64  }).notNull().default('Book Now'),
  ctaRoute:       varchar('cta_route',      { length: 256 }).notNull().default('/(tabs)/services'),
  textPosition:   varchar('text_position',  { length: 20  }).notNull().default('bottom-left'),
  overlayColor:   varchar('overlay_color',  { length: 16  }).notNull().default('#000000'),
  overlayOpacity: real('overlay_opacity').notNull().default(0.3),
  animation:      varchar('animation',      { length: 16  }).notNull().default('slide'),
  priority:       integer('priority').notNull().default(0),
  status:         varchar('status',         { length: 16  }).notNull().default('active'),
  isActive:       boolean('is_active').notNull().default(true),
  sortOrder:      integer('sort_order').notNull().default(0),
  startDate:      timestamp('start_date', { withTimezone: true }),
  endDate:        timestamp('end_date',   { withTimezone: true }),
  expiresAt:      timestamp('expires_at', { withTimezone: true }),
  createdAt:      timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt:      timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt:      timestamp('deleted_at', { withTimezone: true }),
}, (t) => [index('idx_offers_active').on(t.isActive)]);
